### ISSUE TITLE
Decrease brightness of screen 

### ISSUE THREAD

**Issue by cindypoo** [AllenNeuralDynamics/Aind.Behavior.VrForaging#125]
Decrease brightness of screen overall
- too bright to see water droplet coming out
- may be aversive to mice initially (?)

**Comment by bruno-f-cruz** [comment]
I will close this issue for now. For documentation's sake, we decided to:
1. Run screens at full "hardware" brightness. This means all screens should be manually set to the highest brightness setting at all times. Since brightness is controlled via PWM of the backlight, this ensures a continuous brightness signal on the photodiode.
2. Rendered brightness will be controlled via software by the custom shader introduced in #247 and exposed in the rig schema via the `Screen` object
