### ISSUE TITLE
W1 W3 rig assembly in 426

### ISSUE THREAD

**Issue by cindypoo** [AllenNeuralDynamics/Aind.Behavior.VrForaging#187]
Need camera and lenses for these rigs @HeRodrgues 
@travisjramirez please update the parts we are currently missing

**Comment by HeRodrgues** [comment]
The monitors are in the room.
The computer is with IT to reimage, and as soon it's done, I will put it on top of W1.
After talking with @tiffanyona and @axlec, we are moving everything two holes to the front of the box.

**Comment by tiffanyona** [comment]
The schematic for the olfactometer assembling. For future reference, we should update this to a digital format (like the circuit image or something similar)

![image](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/assets/33984148/68e9ee9d-80b0-40a4-91fa-81d6c0ac9fee)

**Comment by cindypoo** [comment]
Agreed. We are in the process of recruiting help from Nathan to do this (rig builds and documentation). I will update you all when I know more when this will be (depends on his other tasks).

**Comment by cindypoo** [comment]
Great, thank you! Please let @nathan-mars know where the computer is. He will work with @tiffanyona + @bruno-f-cruz to test it out with one of the rig builds in progress. 

@HeRodrgues for now we don't anticipate needing your help for the rest of W1 + W3 builds.

**Comment by HeRodrgues** [comment]
Okidoqui @cindypoo.
The computer is in the room, on top of the box, and it needs to be strapped to the box for safety. @nathan-mars, let me know if you need help.
@cindypoo  and @tiffanyona, I would still like to have a schedule of the experiments for the following weeks; I need to work in the room. Just a rough schedule: "From this hour to this hour," you will be running animals.
Thanks

**Comment by cindypoo** [comment]
@HeRodrgues Just to make sure we are talking about the same thing, the computer I am referring to is the small PC that @bruno-f-cruz ordered to test. Is this the computer that is on top of the rig? 

We have been running mice in 426 approximately 9am-2pm. @tiffanyona can let you know more precisely.

**Comment by HeRodrgues** [comment]
The tiny computer is on one of the shelves, on the server rack, and I think there's a cardboard box with the cable and power supply for it.
I'm asking for a schedule because yesterday, the behavior finished at 3:30 pm, and today, it started after 10:30 am. 
Without @travisjramirez are you guys doing the 5 - 6 hours window? And the starting window is at 10.30 am with Olivia?

**Comment by nathan-mars** [comment]
I have the Lenovo Tiny computer in hand now. I'll take a look at it tomorrow.

**Comment by nathan-mars** [comment]
The Tiny computer is hooked up to the VR display in W3 and is working. There isn't a dedicated control monitor right now, so we have to swap HDMI cables from one of the other boxes for now. @tiffanyona and @bruno-f-cruz if you want to start preliminary testing of scripts you can, otherwise let's wait until the box is fully built.

**Comment by tiffanyona** [comment]
Great Nathan! I think we have a monitor mount next to the table that we could place on top and use as the control monitor. We just need to make a bit of space for it. Now that that is on the way of being solved, we should start assembling the main harp boards and connections so we can test the system. The software side of things will be quickly to setup once we are able to interact with the computer.
