### ISSUE TITLE
Draw first state randomly assuming the overal prob of a patch

### ISSUE THREAD

**Issue by tiffanyona** [AllenNeuralDynamics/Aind.Behavior.VrForaging#272]

**Comment by bruno-f-cruz** [comment]
On second thought I don't think we should stretch the definition of transition matrix. I am more inclined to instead add a an additional property / modify the initial state to be a nullable array. A null value will still proceed as it does now, otherwise the probability of drawing a patch will be given my the Nth index. This is more consistent with the idea that a transition matrix does not define the initial condition, only how you transition between them.

**Comment by bruno-f-cruz** [comment]
Closed via [f3b57e2](https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging/commit/f3b57e28bebbb1487fde111dd00a998ca8d7d0ec)
